name: Trade Data Collector CI/CD

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main   # Trigger workflow for pull requests targeting `main` branch

jobs:
  building & formatting:
    name: setup environment
    runs-on: ubuntu-latest  # Set the OS for the runner

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install dependencies
      run: |
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings  # Run clippy to lint the code

    - name: Check formatting
      run: cargo fmt -- --check  # Check formatting with rustfmt

    - name: Build the project
      run: cargo build --release  # Build the project in release mode

  testing:
    name: test code
    runs-on: ubuntu-latest  # Set the OS for the runner
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Run tests
      run: cargo test --verbose -- --nocapture # Run all tests

