name: Trade Data Collector CI/CD

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main   # Trigger workflow for pull requests targeting `main` branch

jobs:
  building:
    name: build
    runs-on: ubuntu-latest  # Set the OS for the runner

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install dependencies
      run: |
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings  # Run clippy to lint the code

    - name: Check formatting
      run: cargo fmt -- --check  # Check formatting with rustfmt

    - name: Build the project
      run: cargo build --release  # Build the project in release mode

  running:
    name: run
    runs-on: ubuntu-latest  # Set the OS for the runner
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: produce csv
      env: 
        MAINNET_ORDERBOOK_CONTRACT: ${{ secrets.MAINNET_ORDERBOOK_CONTRACT }}
        ETHERSCAN_BASE_URL: ${{ secrets.ETHERSCAN_BASE_URL }}
        BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        MAINNET_WS_RPC_URL: ${{ secrets.MAINNET_WS_RPC_URL }}
        BASE_WS_RPC_URL: ${{ secrets.BASE_WS_RPC_URL }}
        ORDERBOOK_ABI_PATH: ${{ secrets.ORDERBOOK_ABI_PATH }}
      run: cargo run -- --contract 0x0ea6d458488d1cf51695e1d6e4744e6fb715d37c

