name: Trade Data Collector CI/CD

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main   # Trigger workflow for pull requests targeting `main` branch

jobs:
  building:
    name: build
    runs-on: ubuntu-latest  # Set the OS for the runner

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install dependencies
      run: |
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings  # Run clippy to lint the code

    - name: Check formatting
      run: cargo fmt -- --check  # Check formatting with rustfmt

    - name: Build the project
      run: cargo build --release  # Build the project in release mode

  running:
    name: run
    runs-on: ubuntu-latest  # Set the OS for the runner
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: produce csv
      env: 
        BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      run: cargo run

