name: Trade Data Collector CI/CD

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main   # Trigger workflow for pull requests targeting `main` branch

jobs:
  building:
    name: build code
    runs-on: ubuntu-latest  # Set the OS for the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rust-version: 1.87.0

    - name: Build the project
      run: cargo build --release  # Build the project in release mode

  formatting:
    name: format code
    runs-on: ubuntu-latest  # Set the OS for the runner
    
    steps:
    - name: Install dependencies
      run: |
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings  # Run clippy to lint the code

    - name: Check formatting
      run: cargo fmt -- --check  # Check formatting with rustfmt

  testing:
    name: test code
    runs-on: ubuntu-latest  # Set the OS for the runner
    
    steps:
    - name: Run tests
      run: cargo test --verbose  # Run all tests

    - name: Run tests on sample dataset (if applicable)
      run: cargo test -- --nocapture  # Optionally run specific tests if needed
